OdeToFood/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System.Diagnostics;

namespace OdeToFood.Pages
{
  [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
  public class ErrorModel : PageModel
  {
    public string RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
      _logger = logger;
    }

    public void OnGet()
    {
      RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
  }
}

OdeToFood/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace OdeToFood.Pages
{
  public class IndexModel : PageModel
  {
    private readonly ILogger<IndexModel> _logger;

    public IndexModel(ILogger<IndexModel> logger)
    {
      _logger = logger;
    }

    public void OnGet()
    {

    }
  }
}

OdeToFood/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace OdeToFood.Pages
{
  public class PrivacyModel : PageModel
  {
    private readonly ILogger<PrivacyModel> _logger;

    public PrivacyModel(ILogger<PrivacyModel> logger)
    {
      _logger = logger;
    }

    public void OnGet()
    {
    }
  }
}

OdeToFood/Pages/Restaurants/ClientRestaurants.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace OdeToFood.Pages.Restaurants
{
    public class ClientRestaurantsModel : PageModel
    {
      
    }
}

OdeToFood/Pages/Restaurants/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OdeToFood.Core;
using OdeToFood.Data;

namespace OdeToFood.Pages.Restaurants
{
  public class DeleteModel : PageModel
  {
    private readonly IRestaurantData restaurantData;
    public Restaurant Restaurant { get; set; }
    
    public DeleteModel(IRestaurantData restaurantData) 
    {
      this.restaurantData = restaurantData;
    }
    public IActionResult OnGet(int restaurantId)
    {
      Restaurant = restaurantData.GetById(restaurantId);
      if(Restaurant == null)
      {
        return RedirectToPage("./NotFound");
      }
      return Page();
    }
    public IActionResult OnPost(int restaurantId)
    {
      var restaurant = restaurantData.Delete(restaurantId);
      restaurantData.Commit();

      if(restaurant == null)
      {
        return RedirectToPage("./NotFound");
      }

      TempData["DeleteMessage"] = $"{restaurant.Name} deleted.";
      return RedirectToPage("./List");
    }
  }
}

OdeToFood/Pages/Restaurants/Detail.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OdeToFood.Core;
using OdeToFood.Data;

namespace OdeToFood
{
  public class DetailModel : PageModel
  {
    private readonly IRestaurantData restaurantData;

    [TempData]
    public string Message { get; set; }
    public Restaurant Restaurant { get; set; }

    public DetailModel(IRestaurantData restaurantData)
    {
      this.restaurantData = restaurantData;
    }
    public IActionResult OnGet(int restaurantId)
    {
      Restaurant = restaurantData.GetById(restaurantId);
      if (Restaurant == null)
      {
        return RedirectToPage("./NotFound");
      }
      return Page();
    }
  }
}

OdeToFood/Pages/Restaurants/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using OdeToFood.Core;
using OdeToFood.Data;
using System.Collections.Generic;

namespace OdeToFood
{
  public class EditModel : PageModel
  {
    private readonly IRestaurantData restaurantData;
    private readonly IHtmlHelper htmlHelper;

    [BindProperty]
    public Restaurant Restaurant { get; set; }
    public IEnumerable<SelectListItem> Cuisines { get; set; }

    public EditModel(IRestaurantData restaurantData,
                     IHtmlHelper htmlHelper)
    {
      this.restaurantData = restaurantData;
      this.htmlHelper = htmlHelper;
    }

    public IActionResult OnGet(int? restaurantId)
    {
      Cuisines = htmlHelper.GetEnumSelectList<CuisineType>();
      if (restaurantId.HasValue)
      {
        Restaurant = restaurantData.GetById(restaurantId.Value);
      }
      else
      {
        Restaurant = new Restaurant();
      }

      if (Restaurant == null)
      {
        return RedirectToPage("./NotFound");
      }
      return Page();
    }

    public IActionResult OnPost()
    {
      if (!ModelState.IsValid)
      {
        Cuisines = htmlHelper.GetEnumSelectList<CuisineType>();
        return Page();
      }

      if (Restaurant.Id > 0)
      {
        restaurantData.Update(Restaurant);
      }
      else
      {
        restaurantData.Add(Restaurant);
      }
      restaurantData.Commit();
      TempData["Message"] = "Restaurant saved!";
      return RedirectToPage("./Detail", new { restaurantId = Restaurant.Id });
    }
  }
}

OdeToFood/Pages/Restaurants/List.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using OdeToFood.Core;
using OdeToFood.Data;
using System.Collections.Generic;

namespace OdeToFood
{
  public class ListModel : PageModel
  {
    private readonly IConfiguration config;
    private readonly IRestaurantData restaurantData;
    private readonly ILogger<ListModel> logger;

    public string Message { get; set; }
    public string DeleteMessage { get; set; }
    public IEnumerable<Restaurant> Restaurants { get; set; }

    [BindProperty(SupportsGet = true)]
    public string SearchTerm { get; set; }

    public ListModel(IConfiguration config, IRestaurantData restaurantData, ILogger<ListModel> logger)
    {
      this.config = config;
      this.restaurantData = restaurantData;
      this.logger = logger;
    }
    public void OnGet()
    {
      Message = config["SecretMessage"];
      logger.LogInformation("Get request to /List");
      Restaurants = restaurantData.GetRestaurantsByName(SearchTerm);
    }
  }
}

OdeToFood/ViewComponents/RestaurantCountViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using OdeToFood.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OdeToFood.ViewComponents
{
  public class RestaurantCountViewComponent : ViewComponent
  {
    private readonly IRestaurantData restaurantData;

    public RestaurantCountViewComponent(IRestaurantData restaurantData)
    {
      this.restaurantData = restaurantData;
    }

    public IViewComponentResult Invoke()
    {
      var count = restaurantData.GetCountOfRestaurants();
      return View(count);
    }
  }
}

OdeToFood/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

OdeToFood/Pages/Restaurants/ClientRestaurants.cshtml
@page
@model OdeToFood.Pages.Restaurants.ClientRestaurantsModel
@{
  ViewData["Title"] = "ClientRestaurants";
}

<h2>Client Restaurants</h2>
<table class="table" id="restaurants"></table>

@section Scripts {
  <environment include="Development">
    <script src="~/node_modules/datatables.net/js/jquery.dataTables.js"></script>
    <script src="~/node_modules/datatables.net-dt/js/dataTables.dataTables.js"></script>
    <link href="~/node_modules/datatables.net-dt/css/jquery.dataTables.css" rel="stylesheet" />
  </environment>
  <environment exclude="Development">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.21/datatables.min.css" />
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.21/datatables.min.js"></script>
  </environment>
  <script>
    $(function () {

      var cuisines = [
        'None',
        'American',
        'Chinese',
        'Indian',
        'Italian',
        'Japanese',
        'Mexican'
      ];

      $.ajax("/api/restaurants/",
        { method: "get" })
        .then(res => {
          $('#restaurants').dataTable({
            data: res,
            columns: [
              {
                title: "Name",
                data: "name"
              },
              {
                title: "Location",
                data: "location"
              },
              {
                title: "Cuisine Type",
                data: "cuisine",
                render: data => cuisines[data]
              }
            ]
          });
          return res;
        })
        .catch(error => console.error(error))
    });
  </script>
}

OdeToFood/Pages/Restaurants/Delete.cshtml
@page "{restaurantId:int}"
@model OdeToFood.Pages.Restaurants.DeleteModel
@{
  ViewData["Title"] = "Delete";
}

<h2>Delete Restaurant</h2>
<div class="alert alert-danger">Are you sure you want to delete @Model.Restaurant.Name?</div>
<form method="post">
  <button type="submit" class="btn btn-danger">Delete</button>
  <a asp-page="List" class="btn btn-default">Cancel</a>
</form>

OdeToFood/Pages/Restaurants/Detail.cshtml
@page "{restaurantId:int}"
@model OdeToFood.DetailModel
@{
  ViewData[ "Title" ] = "Detail";
}

@if ( Model.Message != null )
{
  <div class="alert alert-success">@Model.Message</div>
}

<h1>@Model.Restaurant.Name</h1>
<p>@Model.Restaurant.Id</p>
<p>Location: @Model.Restaurant.Location</p>
<p>Cusine: @Model.Restaurant.Cuisine</p>

<a asp-page="./List" class="btn btn-outline-primary">All Restaurants</a>

OdeToFood/Pages/Restaurants/Edit.cshtml
@page "{restaurantId:int?}"
@model OdeToFood.EditModel
@{
  ViewData["Title"] = "Edit";
}

<h1>Editing: @Model.Restaurant.Name</h1>
<form method="post">
  <input type="hidden" asp-for="Restaurant.Id" />
  <div class="form-group">
    <label asp-for="Restaurant.Name">Name</label>
    <input asp-for="Restaurant.Name" class="form-control" />
    <span class="text-danger" asp-validation-for="Restaurant.Name"></span>
  </div>
  <div class="form-group">
    <label asp-for="Restaurant.Location">Location</label>
    <input asp-for="Restaurant.Location" class="form-control" />
    <span class="text-danger" asp-validation-for="Restaurant.Location"></span>
  </div>
  <div class="form-group">
    <label asp-for="Restaurant.Cuisine">Cuisine Type</label>
    <select asp-for="Restaurant.Cuisine" class="form-control"
            asp-items="Model.Cuisines">
    </select>
    <span class="text-danger" asp-validation-for="Restaurant.Cuisine"></span>
  </div>
  <button type="submit" class="btn btn-primary">Save</button>
  <a asp-page="List" class="btn btn-default">Cancel</a>
</form>
@section Scripts {
  <partial name="_ValidationScriptsPartial" />
}

OdeToFood/Pages/Restaurants/List.cshtml
@page
@model OdeToFood.ListModel
@{
  ViewData["Title"] = "Restaurants";
}

<h1>Restaurants</h1>

@if (Model.DeleteMessage != null)
{
  <div class="alert alert-danger">@Model.DeleteMessage</div>
}

<form method="get">
  <div class="form-group">
    <div class="input-group">
      <input type="search" class="form-control" id="searchTerm" name="searchTerm" value="" asp-for="SearchTerm" />
      <span class="input-group-btn">
        <button class="btn btn-default"><i class="material-icons">search</i></button>
      </span>
    </div>
  </div>
</form>
    @foreach (var restaurant in Model.Restaurants)
    {
      <partial name="_Summary" model="restaurant"/>
    }
<a asp-page="./Edit" class="btn btn-primary">Add New</a>
@section footer {
  <div>@Model.Message</div>
}

OdeToFood/Pages/Restaurants/NotFound.cshtml
@page
@{
    ViewData["Title"] = "NotFound";
}

<h1>Your restaurant was not found.</h1>
<a asp-page="./List" class="btn btn-outline-primary">Back to Restaurants</a>

OdeToFood/Pages/Restaurants/_Summary.cshtml
@using OdeToFood.Core
@model Restaurant 

<div class="card mb-4">
  <div class="card-header">
    <h3>@Model.Name</h3>
  </div>
  <div class="card-body">
    <p>Location: @Model.Location</p>
    <p>Cuisine: @Model.Cuisine</p>
  </div>
  <div class="card-footer">
    <a class="btn btn-default"
        asp-page="./Detail"
        asp-route-restaurantId="@Model.Id">
      <i class="material-icons">pageview</i>
    </a>
    <a class="btn btn-default"
        asp-page="./Edit"
        asp-route-restaurantId="@Model.Id">
      <i class="material-icons">create</i>
    </a>
    <a class="btn btn-default"
        asp-page="./Delete"
        asp-route-restaurantId="@Model.Id">
      <i class="material-icons text-danger">delete_forever</i>
    </a>
  </div>
</div>

OdeToFood/Pages/Shared/Components/RestaurantCount/Default.cshtml
@model int

<div class="card bg-light mt-1">
  <div class="card-body">
    There are @Model restaurants here. <a asp-page="/Restaurants/List">See them all.</a>
  </div>
</div>

OdeToFood/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>@ViewData["Title"] - OdeToFood</title>
  <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
        rel="stylesheet">
  <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">OdeToFood</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                  <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                      <a class="nav-link text-light" asp-area="" asp-page="/Index">Home</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link text-light" asp-area="" asp-page="/Restaurants/List">Restaurants</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link text-light" asp-area="" asp-page="/Privacy">Privacy</a>
                    </li>
                  </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top text-muted mt-4">
      <div class="container">
        <vc:restaurant-count></vc:restaurant-count>
        @RenderSection("footer", required: false)
        <p>&copy; 2020 - OdeToFood - <a asp-area="" asp-page="/Privacy">Privacy</a></p>
        <img src="~/OdeToFood.png" alt="Ode To Food Logo" />
      </div>
    </footer>

    <environment include="Development">
      <script src="~/lib/jquery/dist/jquery.js"></script>
      <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
      <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
      <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.5.0.min.js"
              asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
              asp-fallback-test="window.JQuery"
              crossorigin="anonymous"></script>
      <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/4.4.1/bootstrap.min.js"
              asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
              asp-fallback-test="window.JQuery && window.jQuery.fn && window.jQuery.fn.modal"
              crossorigin="anonymous"></script>
      <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    @RenderSection("Scripts", required: false)
</body>
</html>